# Generated by Django 4.1.4 on 2022-12-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinosaurs',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
    ]
